### ISSUE TITLE
[epic] исследовать постановку задачи

### ISSUE THREAD

**Issue by no-one2k** [no-one2k/basnya#1]
Всё, что относится к постановке задачи: исследования похожих задач, варианты постановки, написание дизайн дока и прочих верхнеуровневых доков

- [x] написать в1 дизайн дока
- [ ] проработать подборку кейсов от evidently
- [ ] написать 3 варианта постановки задачи
- [ ] уточнить MVP этапы в в1 дизайн дока
- [ ] обсудить\согласовать
