### ISSUE TITLE
[epic] собрать данные для этапа discovery

### ISSUE THREAD

**Issue by no-one2k** [no-one2k/basnya#3]
Нужно собрать данные достаточные для экспериментов и исследований. Пока нет необходимости оформлять сбор в пайплайны и прочее.

- [x] собрать игры, боксскоры и плейбайплей за пару сезонов НБА 
- [ ] собрать данные игроков, которые играли в этих сезонах
- [ ] собрать реальные твиты\реддиты про статистику в НБА
